package com.kreative.fourdee.common;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class ColorConstants {
	public static final int BLACK          = 0xFF000000;
	public static final int DARK_GRAY      = 0xFF404040;
	public static final int DARK_GREY      = 0xFF404040;
	public static final int IRON           = 0xFF404040;
	public static final int GRAY           = 0xFF808080;
	public static final int GREY           = 0xFF808080;
	public static final int SILVER         = 0xFFC0C0C0;
	public static final int LIGHT_GRAY     = 0xFFC0C0C0;
	public static final int LIGHT_GREY     = 0xFFC0C0C0;
	public static final int WHITE          = 0xFFFFFFFF;
	public static final int WARM_WHITE_LCD = 0xFFFFF3DC;
	public static final int WARM_WHITE_LED = 0xFFFFDD99;
	public static final int FAIR           = 0xFFFFCC99;
	public static final int BROWN          = 0xFF996633;
	public static final int MAROON         = 0xFF800000;
	public static final int UMBER          = 0xFF804000;
	public static final int OLIVE          = 0xFF808000;
	public static final int PINE           = 0xFF008000;
	public static final int TEAL           = 0xFF008080;
	public static final int NAVY           = 0xFF000080;
	public static final int EGGPLANT       = 0xFF400080;
	public static final int PLUM           = 0xFF800080;
	public static final int RED            = 0xFFFF0000;
	public static final int SCARLET        = 0xFFFF4000;
	public static final int ORANGE         = 0xFFFF8000;
	public static final int GOLD           = 0xFFFFC000;
	public static final int YELLOW         = 0xFFFFFF00;
	public static final int CHARTREUSE     = 0xFF80FF00;
	public static final int GREEN          = 0xFF00FF00;
	public static final int AQUAMARINE     = 0xFF00FF80;
	public static final int CYAN           = 0xFF00FFFF;
	public static final int AZURE          = 0xFF0080FF;
	public static final int BLUE           = 0xFF0000FF;
	public static final int INDIGO         = 0xFF4000FF;
	public static final int VIOLET         = 0xFF8000FF;
	public static final int PURPLE         = 0xFFC000FF;
	public static final int MAGENTA        = 0xFFFF00FF;
	public static final int ROSE           = 0xFFFF0080;
	public static final int CORAL          = 0xFFFF8080;
	public static final int CORANGE        = 0xFFFFC080;
	public static final int LEMON          = 0xFFFFFF80;
	public static final int LIME           = 0xFF80FF80;
	public static final int SKY            = 0xFF80FFFF;
	public static final int FROST          = 0xFF8080FF;
	public static final int LAVENDER       = 0xFFC080FF;
	public static final int PINK           = 0xFFFF80FF;
	
	public static final Map<String, Integer> COLORS;
	static {
		Map<String, Integer> map = new HashMap<String, Integer>();
		map.put("black", BLACK);
		map.put("darkgray", DARK_GRAY);
		map.put("darkgrey", DARK_GREY);
		map.put("iron", IRON);
		map.put("gray", GRAY);
		map.put("grey", GREY);
		map.put("silver", SILVER);
		map.put("lightgray", LIGHT_GRAY);
		map.put("lightgrey", LIGHT_GREY);
		map.put("white", WHITE);
		map.put("warmwhite", WARM_WHITE_LCD);
		map.put("warmwhitelcd", WARM_WHITE_LCD);
		map.put("warmwhiteled", WARM_WHITE_LED);
		map.put("fair", FAIR);
		map.put("brown", BROWN);
		map.put("maroon", MAROON);
		map.put("umber", UMBER);
		map.put("olive", OLIVE);
		map.put("pine", PINE);
		map.put("teal", TEAL);
		map.put("navy", NAVY);
		map.put("eggplant", EGGPLANT);
		map.put("plum", PLUM);
		map.put("red", RED);
		map.put("scarlet", SCARLET);
		map.put("orange", ORANGE);
		map.put("gold", GOLD);
		map.put("yellow", YELLOW);
		map.put("chartreuse", CHARTREUSE);
		map.put("green", GREEN);
		map.put("aquamarine", AQUAMARINE);
		map.put("cyan", CYAN);
		map.put("azure", AZURE);
		map.put("blue", BLUE);
		map.put("indigo", INDIGO);
		map.put("violet", VIOLET);
		map.put("purple", PURPLE);
		map.put("magenta", MAGENTA);
		map.put("rose", ROSE);
		map.put("coral", CORAL);
		map.put("corange", CORANGE);
		map.put("lemon", LEMON);
		map.put("lime", LIME);
		map.put("sky", SKY);
		map.put("frost", FROST);
		map.put("lavender", LAVENDER);
		map.put("pink", PINK);
		map.put("k", BLACK);
		map.put("x", GRAY);
		map.put("w", WHITE);
		map.put("l", WARM_WHITE_LCD);
		map.put("f", FAIR);
		map.put("n", BROWN);
		map.put("r", RED);
		map.put("s", SCARLET);
		map.put("o", ORANGE);
		map.put("d", GOLD);
		map.put("y", YELLOW);
		map.put("h", CHARTREUSE);
		map.put("g", GREEN);
		map.put("a", AQUAMARINE);
		map.put("c", CYAN);
		map.put("z", AZURE);
		map.put("b", BLUE);
		map.put("i", INDIGO);
		map.put("v", VIOLET);
		map.put("p", PURPLE);
		map.put("m", MAGENTA);
		map.put("e", ROSE);
		map.put("j", BLACK);
		map.put("u", BLACK);
		map.put("kx", DARK_GRAY);
		map.put("wx", LIGHT_GRAY);
		map.put("ww", WARM_WHITE_LCD);
		map.put("kr", MAROON);
		map.put("ko", UMBER);
		map.put("ky", OLIVE);
		map.put("kg", PINE);
		map.put("kc", TEAL);
		map.put("kb", NAVY);
		map.put("kv", EGGPLANT);
		map.put("km", PLUM);
		map.put("wr", CORAL);
		map.put("wo", CORANGE);
		map.put("wy", LEMON);
		map.put("wg", LIME);
		map.put("wc", SKY);
		map.put("wb", FROST);
		map.put("wv", LAVENDER);
		map.put("wm", PINK);
		COLORS = Collections.unmodifiableMap(map);
	}
	
	public static int parse(String name) {
		name = name.replaceAll("[^A-Za-z0-9]+", "").trim().toLowerCase();
		if (COLORS.containsKey(name)) {
			return COLORS.get(name);
		} else {
			return 0;
		}
	}
}